name: Build Apps

on:
  push:
    branches: [ master, GUI_dev ]
    paths-ignore:
#      - '.github/**'
      - 'cache/**'
      - 'Fiji.app/**'

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: pipeline
          channels: conda-forge
          channel-priority: disabled
          extra-specs: |
            python=3.8
            numpy=1.21
            caiman
            pyimagej
            openjdk=8
            pysimplegui
      - name: Install cx_Freeze
        run: |
          micromamba install -n pipeline -y --no-channel-priority -c https://marcelotduarte.github.io/packages/conda cx_Freeze
      - name: Run Python
        shell: bash -l {0}
        run: |
          python setup.py build
    

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        python-version: [3.8]
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#        architecture: x64
#    - name: Install dependencies
#      run: |
#        conda install mamba -n base -c conda-forge  --yes
#        mamba env create -n pipeline -c conda-forge caiman pyimagej openjdk=8 numpy=1.21 pysimplegui
#        conda activate pipeline
#        conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze
#    - name: Run setup.py
#      run: |
#        python setup.py
