name: Build Apps

on:
  push:
    branches: [ master, GUI_dev ]
    paths-ignore:
#      - '.github/**'
      - 'cache/**'
      - 'Fiji.app/**'

jobs:
  build-env:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure environment using micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: pipeline
          channels: https://marcelotduarte.github.io/packages/conda, conda-forge
          channel-priority: disabled
          extra-specs: |
            cx_Freeze=6.15.0.dev2
            python=3.8
            numpy=1.21
            caiman=1.9.12
            pyimagej
            openjdk=8
            seaborn
            pysimplegui
#      - name: Install cx_Freeze
#        run: |
#          micromamba install -n pipeline -y --no-channel-priority -c https://marcelotduarte.github.io/packages/conda cx_Freeze
#      - name: Run Python
#        shell: bash -l {0}
#        run: |
#          python setup.py bdist_msi --target-name exe.win-amd64-3.8.msi --target-version 0.1
#          ls -la dist/
#          ls -la build/
#          git status
      # Windows
      # With Powershell:
      - name: Run Python
        shell: powershell
        run: |
          python setup.py bdist_msi --target-name exe.win-amd64-3.8.msi --target-version 0.1
          ls -la dist/
          ls -la build/
          git status