name: Build Apps

on:
  push:
    branches: [ master, GUI_dev ]
    paths-ignore:
      - '.github/**'
      - 'cache/**'
      - 'Fiji.app/**'

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: pipeline
          channels: conda-forge
          channel-priority: disabled
          extra-specs: |
            python=3.8
            numpy=1.21
            caiman
            pyimagej
            openjdk=8
            seaborn
            pysimplegui
      - name: Install cx_Freeze
        run: |
          micromamba install -n pipeline -y --no-channel-priority -c https://marcelotduarte.github.io/packages/conda cx_Freeze
      - name: Run Python
        shell: bash -l {0}
        run: |
          python setup.py build